### ISSUE TITLE
Can't determine TML type if path name contains a period

### ISSUE THREAD

**Issue by boonhapus** [thoughtspot/thoughtspot_tml#17]
The parser is naively implemented.

https://github.com/thoughtspot/thoughtspot_tml/blob/60d218e4d74dbe995f2d2be8611ff252cf392d9f/src/thoughtspot_tml/utils.py#L87

---

```python
Python 3.11.0 (main, Oct 24 2022, 18:26:48) [MSC v.1933 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from thoughtspot_tml import utils
>>> import pathlib
>>>
>>> p = pathlib.Path("/Users/first.last/Downloads/my liveboard in 9.0 + tabs.liveboard.tml")
>>> p.suffixes
['.0 + tabs', '.liveboard', '.tml']
>>>
>>> utils.determine_tml_type(path=p)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\work\thoughtspot\thoughtspot_tml\src\thoughtspot_tml\utils.py", line 117, in determine_tml_type
    raise TMLError("\n".join(lines))
thoughtspot_tml.exceptions.TMLError: could not parse TML type from 'info' or 'path', got '0 + tabs'
from path, '\Users\first.last\Downloads\my liveboard in 9.0 + tabs.liveboard.tml'
>>>
>>> name_and_type_suffix, _, _ = p.name.rpartition(".tml")
>>> name_and_type_suffix.rpartition(".")
('my liveboard in 9.0 + tabs', '.', 'liveboard')
>>>
>>> name, _, tml_type = name_and_type_suffix.rpartition(".")
>>> tml_type
'liveboard'
>>>
```

**Comment by boonhapus** [comment]
Implemented as part of **[v2.0.13](https://github.com/thoughtspot/thoughtspot_tml/releases/tag/v2.0.13)**
