### ISSUE TITLE
ThoughtSpot 9.10.0 EA feature Model contains a python reserved word, 'with'

### ISSUE THREAD

**Issue by boonhapus** [thoughtspot/thoughtspot_tml#18]
The new spec includes the keyword `with` in the schema block. This is a python reserved word. We'll want a pre- and post-processor in `thoughtspot_tml.tml.Worksheet` or `thoughtspot_tml._yaml`. Basic testing shows that replacing `with:` to `with_:` resolves the issue on serialization, but we should evaluate a more robust approach.

https://github.com/thoughtspot/thoughtspot_tml/blob/60d218e4d74dbe995f2d2be8611ff252cf392d9f/src/thoughtspot_tml/_scriptability.py#L424

---

```python
Python 3.11.0 (main, Oct 24 2022, 18:26:48) [MSC v.1933 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from thoughtspot_tml import utils
>>> import pathlib
>>>
>>> p = pathlib.Path("C:\Users\boonhapus\Downloads\tmls-failing\5cb2b688-8531-45a4-9efb-35dbd2104a84.worksheet.tml")
>>> utils.determine_tml_type(path=p)
Traceback (most recent call last):
  File "C:\Users\boonhapus\Downloads\tmls-failing\test.py", line 27, in <module>
    tml = parse_tml_file(str(path))
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\boonhapus\Downloads\tmls-failing\test.py", line 14, in parse_tml_file
    tml_obj = tml_cls.load(path=file_path)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\boonhapus\Downloads\tmls-failing\.venv\Lib\site-packages\thoughtspot_tml\_tml.py", line 195, in load
    raise e from None
  File "C:\Users\boonhapus\Downloads\tmls-failing\.venv\Lib\site-packages\thoughtspot_tml\_tml.py", line 192, in load
    instance = cls.loads(path.read_text(encoding="utf-8"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\boonhapus\Downloads\tmls-failing\.venv\Lib\site-packages\thoughtspot_tml\_tml.py", line 170, in loads
    raise TMLDecodeError(cls, data=document, message=str(e)) from None  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
thoughtspot_tml.exceptions.TMLDecodeError: SchemaInPlaceJoin.__init__() got an unexpected keyword argument 'with'
supplied data does not produce a valid TML (Worksheet) document
'5cb2b688-8531-45a4-9efb-35dbd2104a84.worksheet.tml' is not a valid TML (Worksheet) file
>>>
```

**Comment by boonhapus** [comment]
Resolved in **[V2.0.14](https://github.com/thoughtspot/thoughtspot_tml/releases/tag/v2.0.14)** .
